CREATE TABLE IF NOT EXISTS ACHIEVEMENT (ID INT PRIMARY KEY, INFO VARCHAR(1023), SHORT_INFO VARCHAR(255), PARENT_ID INT);

INSERT INTO ACHIEVEMENT(ID, INFO, SHORT_INFO, PARENT_ID) VALUES (1, 'info1', 'short info 1', 0);
INSERT INTO ACHIEVEMENT(ID, INFO, SHORT_INFO, PARENT_ID) VALUES (2, 'info2', 'short info 2', 1);
INSERT INTO ACHIEVEMENT(ID, INFO, SHORT_INFO, PARENT_ID) VALUES (3, 'info3', 'short info 3', 2);
INSERT INTO ACHIEVEMENT(ID, INFO, SHORT_INFO, PARENT_ID) VALUES (4, 'info4', 'short info 4', 2);
INSERT INTO ACHIEVEMENT(ID, INFO, SHORT_INFO, PARENT_ID) VALUES (5, 'info5', 'short info 5', 2);
INSERT INTO ACHIEVEMENT(ID, INFO, SHORT_INFO, PARENT_ID) VALUES (6, 'info6', 'short info 6', 0);
INSERT INTO ACHIEVEMENT(ID, INFO, SHORT_INFO, PARENT_ID) VALUES (7, 'info7', 'short info 7', 3);
INSERT INTO ACHIEVEMENT(ID, INFO, SHORT_INFO, PARENT_ID) VALUES (8, 'info8', 'short info 8', 6);
INSERT INTO ACHIEVEMENT(ID, INFO, SHORT_INFO, PARENT_ID) VALUES (9, 'info9', 'short info 9', 6);
INSERT INTO ACHIEVEMENT(ID, INFO, SHORT_INFO, PARENT_ID) VALUES (10, 'info10', 'short info 10', 0);