CREATE TABLE IF NOT EXISTS ACHIEVEMENT (ID INT PRIMARY KEY, INFO VARCHAR(1023), SHORT_INFO VARCHAR(255), PARENT_ID INT);

INSERT INTO ACHIEVEMENT(ID, INFO, SHORT_INFO, PARENT_ID) VALUES (1, 'info1', 'short info 1', 0);
INSERT INTO ACHIEVEMENT(ID, INFO, SHORT_INFO, PARENT_ID) VALUES (2, 'info2', 'short info 2', 1);
INSERT INTO ACHIEVEMENT(ID, INFO, SHORT_INFO, PARENT_ID) VALUES (3, 'info3', 'short info 3', 2);
INSERT INTO ACHIEVEMENT(ID, INFO, SHORT_INFO, PARENT_ID) VALUES (4, 'info4', 'short info 4', 2);
INSERT INTO ACHIEVEMENT(ID, INFO, SHORT_INFO, PARENT_ID) VALUES (5, 'info5', 'short info 5', 2);
INSERT INTO ACHIEVEMENT(ID, INFO, SHORT_INFO, PARENT_ID) VALUES (6, 'info6', 'short info 6', 0);
INSERT INTO ACHIEVEMENT(ID, INFO, SHORT_INFO, PARENT_ID) VALUES (7, 'info7', 'short info 7', 3);
INSERT INTO ACHIEVEMENT(ID, INFO, SHORT_INFO, PARENT_ID) VALUES (8, 'info8', 'short info 8', 6);
INSERT INTO ACHIEVEMENT(ID, INFO, SHORT_INFO, PARENT_ID) VALUES (9, 'info9', 'short info 9', 6);
INSERT INTO ACHIEVEMENT(ID, INFO, SHORT_INFO, PARENT_ID) VALUES (10, 'info10', 'short info 10', 0);


CREATE TABLE IF NOT EXISTS NODES (ID INT PRIMARY KEY, VALUE TINYINT NOT NULL, LABEL VARCHAR(255));
INSERT INTO NODES(ID, VALUE, LABEL) VALUES(1, 5, 'ORIGIN');
INSERT INTO NODES(ID, VALUE, LABEL) VALUES(2, 1, 'TEXT 1');
INSERT INTO NODES(ID, VALUE, LABEL) VALUES(3, 1, 'TEXT 2');
INSERT INTO NODES(ID, VALUE, LABEL) VALUES(4, 1, 'TEXT 3');
INSERT INTO NODES(ID, VALUE, LABEL) VALUES(5, 1, 'TEXT 4');
INSERT INTO NODES(ID, VALUE, LABEL) VALUES(6, 1, 'TEXT 5');
INSERT INTO NODES(ID, VALUE, LABEL) VALUES(7, 1, 'TEXT 6');
INSERT INTO NODES(ID, VALUE, LABEL) VALUES(8, 1, 'TEXT 7');
INSERT INTO NODES(ID, VALUE, LABEL) VALUES(9, 1, 'TEXT 8');
INSERT INTO NODES(ID, VALUE, LABEL) VALUES(10, 1, 'TEXT 9');
INSERT INTO NODES(ID, VALUE, LABEL) VALUES(11, 1, 'TEXT 10');
INSERT INTO NODES(ID, VALUE, LABEL) VALUES(12, 1, 'TEXT 11');
INSERT INTO NODES(ID, VALUE, LABEL) VALUES(13, 1, 'TEXT 12');
INSERT INTO NODES(ID, VALUE, LABEL) VALUES(14, 1, 'TEXT 13');
INSERT INTO NODES(ID, VALUE, LABEL) VALUES(15, 1, 'TEXT 14');
INSERT INTO NODES(ID, VALUE, LABEL) VALUES(16, 1, 'TEXT 15');


CREATE TABLE IF NOT EXISTS LINKS (ID INT PRIMARY KEY, SOURCE INT, TO INT, VALUE TINYINT NOT NULL, TITLE VARCHAR(255));
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(1, 0, 1, 9, '1000 BC');
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(2, 0, 2, 5, '700 BC');
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(3, 1, 2, 8, '700 BC');
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(4, 1, 3, 4, '350 BC');
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(5, 1, 4, 2, '300 BC');
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(6, 3, 4, 6, '300 BC');
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(7, 6, 7, 10, '60 BC');
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(8, 2, 7, 1, '60 BC');
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(9, 3, 9, 5, '0');
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(10, 5, 9, 7, '0');
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(11, 1, 11, 2, '80');
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(12, 6, 11, 8, '80');
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(13, 10, 11, 8, '80');
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(14, 4, 12, 4, '100');
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(15, 7, 12, 9, '100');
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(16, 8, 13, 7, '150');
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(17, 9, 13, 10, '150');
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(18, 5, 14, 4, '200');
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(19, 6, 14, 5, '200');
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(20, 4, 15, 3, '300');
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(21, 7, 15, 8, '300');
INSERT INTO LINKS(ID, SOURCE, TO, VALUE, TITLE) VALUES(22, 9, 15, 6, '300');